/**
 * Banco de palavras da Mimica, separado da logica do jogo.
 *
 * Fonte unica compartilhada entre o modo local (componente client) e o seed do
 * banco de dados (modo online). Para adicionar novas categorias ou palavras,
 * basta editar este objeto: o modo local passa a refletir imediatamente e o
 * modo online apos rodar o seed.
 */
export const mimicaWordsData = {
  Animais: [
    "cachorro",
    "gato",
    "leão",
    "elefante",
    "girafa",
    "macaco",
    "pinguim",
    "cavalo",
    "coelho",
    "jacaré",
    "tartaruga",
    "águia",
    "canguru",
    "polvo",
    "borboleta",
  ],
  "Filmes e Séries": [
    "Titanic",
    "Vingadores",
    "Harry Potter",
    "Star Wars",
    "Rei Leão",
    "Frozen",
    "Toy Story",
    "Matrix",
    "Stranger Things",
    "Round 6",
    "La Casa de Papel",
    "Game of Thrones",
    "Breaking Bad",
    "Wandinha",
    "Pantera Negra",
  ],
  Profissões: [
    "médico",
    "bombeiro",
    "professor",
    "advogado",
    "piloto",
    "policial",
    "cozinheiro",
    "dentista",
    "pintor",
    "jardineiro",
    "cabeleireiro",
    "garçom",
    "fotógrafo",
    "mecânico",
    "palhaço",
  ],
  Objetos: [
    "guarda-chuva",
    "telefone",
    "óculos",
    "violão",
    "vassoura",
    "tesoura",
    "escova de dente",
    "máquina fotográfica",
    "controle remoto",
    "chave",
    "martelo",
    "abajur",
    "relógio",
    "binóculo",
    "leque",
  ],
  Esportes: [
    "futebol",
    "vôlei",
    "basquete",
    "tênis",
    "natação",
    "boxe",
    "surfe",
    "skate",
    "ciclismo",
    "judô",
    "golfe",
    "esgrima",
    "patinação",
    "escalada",
    "arco e flecha",
  ],
  Comidas: [
    "pizza",
    "hambúrguer",
    "sushi",
    "espaguete",
    "sorvete",
    "pipoca",
    "cachorro-quente",
    "melancia",
    "ovo frito",
    "churrasco",
    "brigadeiro",
    "taco",
    "banana",
    "bolo",
    "café",
  ],
  Lugares: [
    "praia",
    "escola",
    "hospital",
    "igreja",
    "academia",
    "aeroporto",
    "supermercado",
    "cinema",
    "praça",
    "montanha",
    "deserto",
    "floresta",
    "estádio",
    "biblioteca",
    "restaurante",
  ],
  "Personagens Famosos": [
    "Batman",
    "Homem-Aranha",
    "Mickey Mouse",
    "Bob Esponja",
    "Mário",
    "Sonic",
    "Shrek",
    "Minion",
    "Coringa",
    "Mulher-Maravilha",
    "Darth Vader",
    "Hulk",
    "Pikachu",
    "Naruto",
    "Goku",
  ],
} satisfies Record<string, string[]>;

export type MimicaCategory = keyof typeof mimicaWordsData;

/**
 * Ordem de exibicao preferida das categorias. Categorias fora desta lista
 * aparecem no final, em ordem alfabetica.
 */
export const mimicaCategoryOrder: string[] = Object.keys(mimicaWordsData);
