/**
 * Banco de perguntas do Palpite Certo, separado da logica do jogo.
 *
 * Toda pergunta tem como resposta um unico numero. `unit` e `emoji` existem
 * para a tela de revelacao montar "🍦 Resposta correta / 17 litros" sem
 * hardcode na interface. Para adicionar perguntas, basta editar esta lista;
 * o seed faz a carga de forma idempotente pelo enunciado.
 *
 * Valores aproximados por natureza (populacao, recordes, medias) usam a
 * estimativa mais divulgada. Como o jogo premia proximidade e nao exatidao,
 * pequenas defasagens nao prejudicam a partida.
 */
export type PalpiteCertoQuestionData = {
  question: string;
  correctValue: number;
  unit: string | null;
  emoji: string | null;
};

export const palpiteCertoQuestionsData: PalpiteCertoQuestionData[] = [
  // Corpo humano
  {
    question: "Quantos ossos possui um bebê ao nascer?",
    correctValue: 300,
    unit: "ossos",
    emoji: "👶",
  },
  {
    question: "Quantos ossos possui o corpo de um adulto?",
    correctValue: 206,
    unit: "ossos",
    emoji: "🦴",
  },
  {
    question: "Quantos dentes tem um adulto com a dentição completa?",
    correctValue: 32,
    unit: "dentes",
    emoji: "🦷",
  },
  {
    question: "Quantas vezes o coração humano bate por minuto, em média, em repouso?",
    correctValue: 72,
    unit: "batimentos por minuto",
    emoji: "❤️",
  },
  {
    question: "Quantos litros de sangue circulam no corpo de um adulto?",
    correctValue: 5,
    unit: "litros",
    emoji: "🩸",
  },
  {
    question: "Quantos músculos existem no corpo humano?",
    correctValue: 639,
    unit: "músculos",
    emoji: "💪",
  },
  {
    question: "Quantos fios de cabelo tem uma cabeça humana, em média?",
    correctValue: 100000,
    unit: "fios",
    emoji: "💇",
  },
  {
    question: "Quantos quilômetros de vasos sanguíneos existem no corpo humano?",
    correctValue: 100000,
    unit: "quilômetros",
    emoji: "🫀",
  },
  {
    question: "Quantas vezes uma pessoa pisca por minuto, em média?",
    correctValue: 17,
    unit: "vezes por minuto",
    emoji: "👁️",
  },
  {
    question: "Quantos dias dura, em média, uma gestação humana?",
    correctValue: 280,
    unit: "dias",
    emoji: "🤰",
  },
  {
    question: "Qual é a temperatura média do corpo humano em graus Celsius?",
    correctValue: 36.5,
    unit: "graus Celsius",
    emoji: "🌡️",
  },
  {
    question: "Quantos litros de saliva uma pessoa produz por dia, em média?",
    correctValue: 1.5,
    unit: "litros",
    emoji: "💧",
  },

  // Geografia e mundo
  {
    question: "Quantos quilômetros tem a Muralha da China?",
    correctValue: 21196,
    unit: "quilômetros",
    emoji: "🧱",
  },
  {
    question: "Quantos habitantes possui o Japão?",
    correctValue: 123000000,
    unit: "habitantes",
    emoji: "🇯🇵",
  },
  {
    question: "Quantos habitantes possui o Brasil?",
    correctValue: 213000000,
    unit: "habitantes",
    emoji: "🇧🇷",
  },
  {
    question: "Quantos países existem no mundo reconhecidos pela ONU?",
    correctValue: 193,
    unit: "países",
    emoji: "🌍",
  },
  {
    question: "Quantos metros de altura tem o Monte Everest?",
    correctValue: 8849,
    unit: "metros",
    emoji: "🏔️",
  },
  {
    question: "Quantos quilômetros tem o Rio Amazonas?",
    correctValue: 6992,
    unit: "quilômetros",
    emoji: "🌊",
  },
  {
    question: "Quantos estados tem o Brasil, sem contar o Distrito Federal?",
    correctValue: 26,
    unit: "estados",
    emoji: "🗺️",
  },
  {
    question: "Quantos metros de altura tem o Cristo Redentor, sem o pedestal?",
    correctValue: 30,
    unit: "metros",
    emoji: "🙌",
  },
  {
    question: "Quantos metros de altura tem a Torre Eiffel?",
    correctValue: 330,
    unit: "metros",
    emoji: "🗼",
  },
  {
    question: "Quantos metros de altura tem o Burj Khalifa, o prédio mais alto do mundo?",
    correctValue: 828,
    unit: "metros",
    emoji: "🏙️",
  },
  {
    question: "Quantos quilômetros de extensão tem o litoral brasileiro?",
    correctValue: 7491,
    unit: "quilômetros",
    emoji: "🏖️",
  },
  {
    question: "Quantos fusos horários existem no mundo?",
    correctValue: 24,
    unit: "fusos",
    emoji: "🕐",
  },
  {
    question: "Quantos metros de queda tem a maior cachoeira do mundo, o Salto Ángel?",
    correctValue: 979,
    unit: "metros",
    emoji: "💦",
  },
  {
    question: "Quantos habitantes tem a cidade de São Paulo?",
    correctValue: 11450000,
    unit: "habitantes",
    emoji: "🌆",
  },
  {
    question: "Quantos municípios existem no Brasil?",
    correctValue: 5570,
    unit: "municípios",
    emoji: "📍",
  },
  {
    question: "Quantos quilômetros quadrados tem o território brasileiro?",
    correctValue: 8510000,
    unit: "km²",
    emoji: "🇧🇷",
  },
  {
    question: "Quantos degraus tem a escadaria Selarón, no Rio de Janeiro?",
    correctValue: 215,
    unit: "degraus",
    emoji: "🪜",
  },

  // Espaço e ciência
  {
    question: "Quantos quilômetros a luz percorre em um segundo?",
    correctValue: 299792,
    unit: "quilômetros",
    emoji: "💡",
  },
  {
    question: "Quantos milhões de quilômetros separam a Terra do Sol?",
    correctValue: 150,
    unit: "milhões de quilômetros",
    emoji: "☀️",
  },
  {
    question: "Quantos minutos a luz do Sol leva para chegar à Terra?",
    correctValue: 8,
    unit: "minutos",
    emoji: "🌞",
  },
  {
    question: "Quantas luas tem o planeta Júpiter?",
    correctValue: 95,
    unit: "luas",
    emoji: "🪐",
  },
  {
    question: "Quantos dias a Lua leva para dar uma volta completa ao redor da Terra?",
    correctValue: 27,
    unit: "dias",
    emoji: "🌙",
  },
  {
    question: "Quantos graus Celsius tem a temperatura na superfície do Sol?",
    correctValue: 5500,
    unit: "graus Celsius",
    emoji: "🔥",
  },
  {
    question: "Quantos elementos químicos existem na tabela periódica?",
    correctValue: 118,
    unit: "elementos",
    emoji: "🧪",
  },
  {
    question: "Em quantos dias a Terra completa uma volta ao redor do Sol?",
    correctValue: 365,
    unit: "dias",
    emoji: "🌍",
  },
  {
    question: "Quantos quilômetros por hora a Terra gira no equador?",
    correctValue: 1670,
    unit: "km/h",
    emoji: "🌐",
  },
  {
    question: "Quantos anos tem o planeta Terra, em bilhões?",
    correctValue: 4.5,
    unit: "bilhões de anos",
    emoji: "🪨",
  },
  {
    question: "Quantos quilômetros de altitude tem a Estação Espacial Internacional?",
    correctValue: 400,
    unit: "quilômetros",
    emoji: "🛰️",
  },
  {
    question: "Quantas pessoas já pisaram na Lua?",
    correctValue: 12,
    unit: "pessoas",
    emoji: "👨‍🚀",
  },
  {
    question: "Quantos por cento da superfície da Terra é coberta por água?",
    correctValue: 71,
    unit: "por cento",
    emoji: "🌊",
  },
  {
    question: "Quantos metros de profundidade tem a Fossa das Marianas?",
    correctValue: 10994,
    unit: "metros",
    emoji: "🌑",
  },
  {
    question: "Quantos graus Celsius abaixo de zero é o zero absoluto?",
    correctValue: 273,
    unit: "graus Celsius negativos",
    emoji: "🧊",
  },

  // Animais
  {
    question: "Quantos corações tem um polvo?",
    correctValue: 3,
    unit: "corações",
    emoji: "🐙",
  },
  {
    question: "Quantos anos vive uma tartaruga-gigante, em média?",
    correctValue: 100,
    unit: "anos",
    emoji: "🐢",
  },
  {
    question: "Quantos quilômetros por hora corre um guepardo em velocidade máxima?",
    correctValue: 110,
    unit: "km/h",
    emoji: "🐆",
  },
  {
    question: "Quantos ovos uma galinha bota por ano, em média?",
    correctValue: 300,
    unit: "ovos",
    emoji: "🥚",
  },
  {
    question: "Quantas patas tem uma aranha?",
    correctValue: 8,
    unit: "patas",
    emoji: "🕷️",
  },
  {
    question: "Quantos quilos pesa a língua de uma baleia-azul?",
    correctValue: 2700,
    unit: "quilos",
    emoji: "🐋",
  },
  {
    question: "Quantas vezes por segundo um beija-flor bate as asas?",
    correctValue: 70,
    unit: "vezes por segundo",
    emoji: "🐦",
  },
  {
    question: "Quantos dentes tem um tubarão-branco na boca ao mesmo tempo?",
    correctValue: 300,
    unit: "dentes",
    emoji: "🦈",
  },
  {
    question: "Quantos meses dura a gestação de uma elefanta?",
    correctValue: 22,
    unit: "meses",
    emoji: "🐘",
  },
  {
    question: "Quantas horas por dia um coala dorme?",
    correctValue: 20,
    unit: "horas",
    emoji: "🐨",
  },
  {
    question: "Quantos quilos pode pesar um urso-polar macho adulto?",
    correctValue: 600,
    unit: "quilos",
    emoji: "🐻‍❄️",
  },
  {
    question: "Quantas espécies de aves existem no Brasil?",
    correctValue: 1971,
    unit: "espécies",
    emoji: "🦜",
  },

  // Comida e bebida
  {
    question: "Quantos litros de sorvete são consumidos por pessoa, em média, por ano no Brasil?",
    correctValue: 6,
    unit: "litros",
    emoji: "🍦",
  },
  {
    question: "Quantas xícaras de café um brasileiro toma por dia, em média?",
    correctValue: 3,
    unit: "xícaras",
    emoji: "☕",
  },
  {
    question: "Quantas calorias tem uma banana média?",
    correctValue: 105,
    unit: "calorias",
    emoji: "🍌",
  },
  {
    question: "Quantos grãos de café são necessários para uma xícara de espresso?",
    correctValue: 50,
    unit: "grãos",
    emoji: "☕",
  },
  {
    question: "Quantos litros de água são necessários para produzir um quilo de carne bovina?",
    correctValue: 15000,
    unit: "litros",
    emoji: "🥩",
  },
  {
    question: "Quantas variedades de queijo existem na França?",
    correctValue: 1200,
    unit: "variedades",
    emoji: "🧀",
  },
  {
    question: "Quantos quilos de açúcar um brasileiro consome por ano, em média?",
    correctValue: 50,
    unit: "quilos",
    emoji: "🍬",
  },
  {
    question: "Quantas pizzas são vendidas por dia na cidade de São Paulo?",
    correctValue: 1000000,
    unit: "pizzas",
    emoji: "🍕",
  },
  {
    question: "Quantos anos leva para uma garrafa de vinho tinto atingir o auge, em média?",
    correctValue: 10,
    unit: "anos",
    emoji: "🍷",
  },
  {
    question: "Quantas sementes tem um morango, em média, na parte de fora?",
    correctValue: 200,
    unit: "sementes",
    emoji: "🍓",
  },

  // Esportes
  {
    question: "Quantos jogadores entram em campo em uma partida de futebol, somando os dois times?",
    correctValue: 22,
    unit: "jogadores",
    emoji: "⚽",
  },
  {
    question: "Quantas Copas do Mundo o Brasil venceu?",
    correctValue: 5,
    unit: "títulos",
    emoji: "🏆",
  },
  {
    question: "Quantos gols Pelé marcou na carreira, segundo a contagem oficial do Santos?",
    correctValue: 1283,
    unit: "gols",
    emoji: "👑",
  },
  {
    question: "Quantos metros tem uma piscina olímpica de comprimento?",
    correctValue: 50,
    unit: "metros",
    emoji: "🏊",
  },
  {
    question: "Quantos quilômetros tem uma maratona oficial?",
    correctValue: 42,
    unit: "quilômetros",
    emoji: "🏃",
  },
  {
    question: "Quantas medalhas olímpicas de ouro Michael Phelps conquistou?",
    correctValue: 23,
    unit: "medalhas de ouro",
    emoji: "🥇",
  },
  {
    question: "Quantos centímetros de altura tem a cesta em uma quadra oficial de basquete?",
    correctValue: 305,
    unit: "centímetros",
    emoji: "🏀",
  },
  {
    question: "Quantas voltas tem o Grande Prêmio do Brasil de Fórmula 1 em Interlagos?",
    correctValue: 71,
    unit: "voltas",
    emoji: "🏎️",
  },
  {
    question: "Quantos anos tinha Pelé quando venceu sua primeira Copa do Mundo?",
    correctValue: 17,
    unit: "anos",
    emoji: "🌟",
  },
  {
    question: "Quantos buracos tem um campo de golfe oficial?",
    correctValue: 18,
    unit: "buracos",
    emoji: "⛳",
  },

  // Cultura e entretenimento
  {
    question: "Quantos episódios tem a série Friends no total?",
    correctValue: 236,
    unit: "episódios",
    emoji: "📺",
  },
  {
    question: "Quantas teclas tem um piano completo?",
    correctValue: 88,
    unit: "teclas",
    emoji: "🎹",
  },
  {
    question: "Quantos minutos dura o filme Titanic?",
    correctValue: 194,
    unit: "minutos",
    emoji: "🚢",
  },
  {
    question: "Quantas cordas tem um violão comum?",
    correctValue: 6,
    unit: "cordas",
    emoji: "🎸",
  },
  {
    question: "Quantos Oscars o filme Titanic ganhou?",
    correctValue: 11,
    unit: "estatuetas",
    emoji: "🏅",
  },
  {
    question: "Quantos livros tem a série Harry Potter?",
    correctValue: 7,
    unit: "livros",
    emoji: "⚡",
  },
  {
    question: "Quantas peças tem um tabuleiro de xadrez no início da partida?",
    correctValue: 32,
    unit: "peças",
    emoji: "♟️",
  },
  {
    question: "Quantos países participam do Festival Eurovision, em média, por edição?",
    correctValue: 40,
    unit: "países",
    emoji: "🎤",
  },
  {
    question: "Quantas cartas tem um baralho completo, incluindo os coringas?",
    correctValue: 54,
    unit: "cartas",
    emoji: "🃏",
  },
  {
    question: "Em que ano começou a construção da Sagrada Família, em Barcelona?",
    correctValue: 1882,
    unit: null,
    emoji: "⛪",
  },

  // Tecnologia
  {
    question: "Quantos usuários ativos por mês o WhatsApp tem, em bilhões?",
    correctValue: 2.8,
    unit: "bilhões de usuários",
    emoji: "💬",
  },
  {
    question: "Em que ano foi lançado o primeiro iPhone?",
    correctValue: 2007,
    unit: null,
    emoji: "📱",
  },
  {
    question: "Quantos e-mails são enviados no mundo por dia, em bilhões?",
    correctValue: 350,
    unit: "bilhões de e-mails",
    emoji: "📧",
  },
  {
    question: "Quantas horas de vídeo são enviadas ao YouTube por minuto?",
    correctValue: 500,
    unit: "horas",
    emoji: "▶️",
  },
  {
    question: "Quantos bytes tem um megabyte?",
    correctValue: 1048576,
    unit: "bytes",
    emoji: "💾",
  },
  {
    question: "Em que ano a internet comercial chegou ao Brasil?",
    correctValue: 1995,
    unit: null,
    emoji: "🌐",
  },
  {
    question: "Quantas buscas o Google processa por segundo, em milhares?",
    correctValue: 99,
    unit: "milhares de buscas",
    emoji: "🔍",
  },
  {
    question: "Quantos satélites artificiais estão em órbita da Terra?",
    correctValue: 10000,
    unit: "satélites",
    emoji: "🛰️",
  },

  // Curiosidades e cotidiano
  {
    question: "Quantos litros de água uma pessoa gasta em um banho de 10 minutos?",
    correctValue: 100,
    unit: "litros",
    emoji: "🚿",
  },
  {
    question: "Quantos passos uma pessoa dá por dia, em média?",
    correctValue: 5000,
    unit: "passos",
    emoji: "🚶",
  },
  {
    question: "Quantos anos uma pessoa passa dormindo, em média, ao longo da vida?",
    correctValue: 26,
    unit: "anos",
    emoji: "😴",
  },
  {
    question: "Quantos idiomas são falados no mundo?",
    correctValue: 7000,
    unit: "idiomas",
    emoji: "🗣️",
  },
  {
    question: "Quantas pessoas nascem no mundo por minuto?",
    correctValue: 250,
    unit: "nascimentos",
    emoji: "🍼",
  },
  {
    question: "Quantos dias uma pessoa passa esperando em filas ao longo da vida?",
    correctValue: 200,
    unit: "dias",
    emoji: "⏳",
  },
  {
    question: "Quantos quilos de lixo um brasileiro produz por dia, em média?",
    correctValue: 1,
    unit: "quilo",
    emoji: "🗑️",
  },
  {
    question: "Quantos anos leva para uma garrafa PET se decompor na natureza?",
    correctValue: 400,
    unit: "anos",
    emoji: "♻️",
  },
  {
    question: "Quantas vezes uma folha de papel pode ser dobrada ao meio, na prática?",
    correctValue: 7,
    unit: "vezes",
    emoji: "📄",
  },
  {
    question: "Quantos segundos tem um dia?",
    correctValue: 86400,
    unit: "segundos",
    emoji: "⏱️",
  },
  {
    question: "Quantas notas musicais diferentes existem na escala cromática?",
    correctValue: 12,
    unit: "notas",
    emoji: "🎵",
  },
  {
    question: "Quantos quilômetros uma pessoa caminha, em média, ao longo da vida?",
    correctValue: 120000,
    unit: "quilômetros",
    emoji: "👟",
  },

  // Espaço profundo e astronomia
  {
    question: "Quantos anos-luz separam a Terra da estrela Proxima Centauri?",
    correctValue: 4,
    unit: "anos-luz",
    emoji: "⭐",
  },
  {
    question: "Quantos quilômetros de diâmetro tem o Sol?",
    correctValue: 1392000,
    unit: "quilômetros",
    emoji: "☀️",
  },
  {
    question: "Quantos quilômetros de diâmetro tem Júpiter?",
    correctValue: 139820,
    unit: "quilômetros",
    emoji: "🪐",
  },
  {
    question: "Quantos dias terrestres dura um dia completo em Vênus?",
    correctValue: 243,
    unit: "dias",
    emoji: "♀️",
  },
  {
    question: "Quantos graus Celsius atinge a superfície de Vênus?",
    correctValue: 464,
    unit: "graus Celsius",
    emoji: "🌋",
  },
  {
    question: "Quantos anos terrestres Netuno leva para dar uma volta ao redor do Sol?",
    correctValue: 165,
    unit: "anos",
    emoji: "🔵",
  },
  {
    question: "Quantos quilômetros de largura têm os anéis de Saturno?",
    correctValue: 282000,
    unit: "quilômetros",
    emoji: "💫",
  },
  {
    question: "Quantas luas conhecidas tem Saturno?",
    correctValue: 146,
    unit: "luas",
    emoji: "🌗",
  },
  {
    question: "Quantos quilômetros por segundo é a velocidade de escape da Terra?",
    correctValue: 11,
    unit: "km/s",
    emoji: "🚀",
  },
  {
    question: "Quantos anos-luz de diâmetro tem a Via Láctea?",
    correctValue: 100000,
    unit: "anos-luz",
    emoji: "🌌",
  },
  {
    question: "Quantas estrelas tem a Via Láctea, em bilhões?",
    correctValue: 200,
    unit: "bilhões de estrelas",
    emoji: "✨",
  },
  {
    question: "Quantos anos-luz nos separam do centro da Via Láctea?",
    correctValue: 26000,
    unit: "anos-luz",
    emoji: "🌌",
  },
  {
    question: "Quantos anos-luz nos separam da galáxia de Andrômeda?",
    correctValue: 2537000,
    unit: "anos-luz",
    emoji: "🌠",
  },
  {
    question: "Quantos bilhões de anos tem o universo?",
    correctValue: 14,
    unit: "bilhões de anos",
    emoji: "💥",
  },
  {
    question: "Quantos minutos a luz do Sol leva para chegar a Netuno?",
    correctValue: 250,
    unit: "minutos",
    emoji: "🔭",
  },
  {
    question: "Quantas toneladas pesaria uma colher de chá de estrela de nêutrons?",
    correctValue: 1000000000,
    unit: "toneladas",
    emoji: "⚫",
  },
  {
    question: "Quantos quilômetros de diâmetro tem uma estrela de nêutrons típica?",
    correctValue: 20,
    unit: "quilômetros",
    emoji: "🌟",
  },
  {
    question: "Quantas rotações por segundo faz o pulsar mais rápido já observado?",
    correctValue: 716,
    unit: "rotações por segundo",
    emoji: "📡",
  },
  {
    question: "Quantos quilômetros de largura tem a Grande Mancha Vermelha de Júpiter?",
    correctValue: 16000,
    unit: "quilômetros",
    emoji: "🔴",
  },
  {
    question: "Quantos bilhões de quilômetros a sonda Voyager 1 já percorreu?",
    correctValue: 24,
    unit: "bilhões de quilômetros",
    emoji: "🛸",
  },
  {
    question: "Quantos quilos pesava o Sputnik 1, o primeiro satélite artificial?",
    correctValue: 83,
    unit: "quilos",
    emoji: "🛰️",
  },
  {
    question: "Quantos dias durou a missão Apollo 11?",
    correctValue: 8,
    unit: "dias",
    emoji: "🌕",
  },
  {
    question: "Quantos quilos de rochas lunares a Apollo 11 trouxe para a Terra?",
    correctValue: 21,
    unit: "quilos",
    emoji: "🪨",
  },
  {
    question: "Quantos segundos durou o primeiro voo dos irmãos Wright?",
    correctValue: 12,
    unit: "segundos",
    emoji: "✈️",
  },
  {
    question: "Quantos quilômetros de altura tem o Monte Olimpo, o maior vulcão de Marte?",
    correctValue: 22,
    unit: "quilômetros",
    emoji: "🔺",
  },
  {
    question: "Quantos quilômetros de extensão tem o Valles Marineris, em Marte?",
    correctValue: 4000,
    unit: "quilômetros",
    emoji: "🏜️",
  },
  {
    question: "Quantos graus Celsius abaixo de zero é a temperatura média de Marte?",
    correctValue: 63,
    unit: "graus Celsius negativos",
    emoji: "🔴",
  },
  {
    question: "Quantos por cento da massa do sistema solar está concentrada no Sol?",
    correctValue: 99,
    unit: "por cento",
    emoji: "☀️",
  },
  {
    question: "Quantos quilômetros de diâmetro tem Ceres, o maior asteroide do cinturão?",
    correctValue: 940,
    unit: "quilômetros",
    emoji: "☄️",
  },
  {
    question: "Quantos quilômetros de diâmetro tem Plutão?",
    correctValue: 2377,
    unit: "quilômetros",
    emoji: "🧊",
  },
  {
    question: "Quantos anos Plutão leva para completar uma órbita ao redor do Sol?",
    correctValue: 248,
    unit: "anos",
    emoji: "🪐",
  },
  {
    question: "Quantos minutos dura, no máximo, a totalidade de um eclipse solar?",
    correctValue: 7,
    unit: "minutos",
    emoji: "🌑",
  },
  {
    question: "Quantos quilômetros por hora atingem os ventos de Netuno?",
    correctValue: 2100,
    unit: "km/h",
    emoji: "🌬️",
  },
  {
    question: "Quantas luas conhecidas tem Urano?",
    correctValue: 28,
    unit: "luas",
    emoji: "🌘",
  },
  {
    question: "Quantos graus está inclinado o eixo de rotação de Urano?",
    correctValue: 98,
    unit: "graus",
    emoji: "🧭",
  },
  {
    question: "Quantos anos-luz nos separam da Nebulosa de Órion?",
    correctValue: 1344,
    unit: "anos-luz",
    emoji: "🌫️",
  },
  {
    question: "Quantos segmentos hexagonais formam o espelho do telescópio James Webb?",
    correctValue: 18,
    unit: "segmentos",
    emoji: "🔭",
  },
  {
    question: "Quantos quilômetros separam o telescópio James Webb da Terra?",
    correctValue: 1500000,
    unit: "quilômetros",
    emoji: "🛰️",
  },
  {
    question: "Quantos países participam do programa da Estação Espacial Internacional?",
    correctValue: 15,
    unit: "países",
    emoji: "🌍",
  },
  {
    question: "Quantas voltas ao redor da Terra a Estação Espacial dá por dia?",
    correctValue: 16,
    unit: "voltas",
    emoji: "🔄",
  },
  {
    question: "Quantos quilômetros por hora viaja a Estação Espacial Internacional?",
    correctValue: 27600,
    unit: "km/h",
    emoji: "💨",
  },
  {
    question: "Quantos dias seguidos durou a permanência mais longa de um humano no espaço?",
    correctValue: 437,
    unit: "dias",
    emoji: "👨‍🚀",
  },
  {
    question: "Quantos quilos pesa um traje espacial completo da NASA?",
    correctValue: 127,
    unit: "quilos",
    emoji: "🧑‍🚀",
  },
  {
    question: "Quantos milhões de graus Celsius tem o núcleo do Sol?",
    correctValue: 15,
    unit: "milhões de graus",
    emoji: "🔥",
  },
  {
    question: "Quantos bilhões de anos de vida o Sol ainda tem pela frente?",
    correctValue: 5,
    unit: "bilhões de anos",
    emoji: "🌅",
  },
  {
    question: "Quantas camadas tem a atmosfera da Terra?",
    correctValue: 5,
    unit: "camadas",
    emoji: "🌤️",
  },
  {
    question: "Quantos quilômetros de altitude marca a linha de Kármán, o limite do espaço?",
    correctValue: 100,
    unit: "quilômetros",
    emoji: "🚀",
  },
  {
    question: "Quantos quilômetros de altitude tem a camada de ozônio?",
    correctValue: 25,
    unit: "quilômetros",
    emoji: "🛡️",
  },
  {
    question: "Quantas crateras de impacto confirmadas existem na Terra?",
    correctValue: 190,
    unit: "crateras",
    emoji: "🕳️",
  },
  {
    question: "Quantos anos tem o meteorito mais antigo já encontrado, em bilhões?",
    correctValue: 5,
    unit: "bilhões de anos",
    emoji: "☄️",
  },

  // Ciência, física e química
  {
    question: "Quantos graus Celsius é o ponto de fusão do tungstênio?",
    correctValue: 3422,
    unit: "graus Celsius",
    emoji: "🔩",
  },
  {
    question: "Quantos graus Celsius é o ponto de fusão do ouro?",
    correctValue: 1064,
    unit: "graus Celsius",
    emoji: "🥇",
  },
  {
    question: "Quantos metros por segundo o som viaja no ar?",
    correctValue: 343,
    unit: "metros por segundo",
    emoji: "🔊",
  },
  {
    question: "Quantos metros por segundo o som viaja na água?",
    correctValue: 1480,
    unit: "metros por segundo",
    emoji: "🌊",
  },
  {
    question: "Quantos decibéis atinge o som de um foguete decolando?",
    correctValue: 180,
    unit: "decibéis",
    emoji: "🚀",
  },
  {
    question: "Quantos decibéis é o limite a partir do qual o som causa dor?",
    correctValue: 120,
    unit: "decibéis",
    emoji: "👂",
  },
  {
    question: "Quantos volts tem um raio, em milhões?",
    correctValue: 100,
    unit: "milhões de volts",
    emoji: "⚡",
  },
  {
    question: "Quantos graus Celsius atinge o ar dentro de um raio?",
    correctValue: 30000,
    unit: "graus Celsius",
    emoji: "🌩️",
  },
  {
    question: "Quantos raios atingem a Terra por segundo, no mundo todo?",
    correctValue: 100,
    unit: "raios por segundo",
    emoji: "⛈️",
  },
  {
    question: "Quantos quilômetros por hora um raio se desloca?",
    correctValue: 440000,
    unit: "km/h",
    emoji: "⚡",
  },
  {
    question: "Quantos átomos de hidrogênio cabem lado a lado em um milímetro, em milhões?",
    correctValue: 10,
    unit: "milhões de átomos",
    emoji: "⚛️",
  },
  {
    question: "Quantos anos dura a meia-vida do carbono-14?",
    correctValue: 5730,
    unit: "anos",
    emoji: "🧪",
  },
  {
    question: "Quantos anos dura a meia-vida do urânio-238, em bilhões?",
    correctValue: 4,
    unit: "bilhões de anos",
    emoji: "☢️",
  },
  {
    question: "Quantos graus Celsius ferve a água no topo do Everest?",
    correctValue: 70,
    unit: "graus Celsius",
    emoji: "🫖",
  },
  {
    question: "Quantas moléculas de água existem em uma única gota, em sextilhões?",
    correctValue: 1,
    unit: "sextilhão de moléculas",
    emoji: "💧",
  },
  {
    question: "Quantos litros de ar uma pessoa respira por dia?",
    correctValue: 11000,
    unit: "litros",
    emoji: "🌬️",
  },
  {
    question: "Quantos por cento do ar que respiramos é nitrogênio?",
    correctValue: 78,
    unit: "por cento",
    emoji: "💨",
  },
  {
    question: "Quantos quilos de pressão atmosférica o corpo humano suporta ao nível do mar?",
    correctValue: 1000,
    unit: "quilos",
    emoji: "🏋️",
  },
  {
    question: "Quantos quilômetros por hora cai uma gota de chuva?",
    correctValue: 32,
    unit: "km/h",
    emoji: "🌧️",
  },
  {
    question: "Quantos cristais diferentes de gelo já foram catalogados pela ciência?",
    correctValue: 20,
    unit: "formas de gelo",
    emoji: "❄️",
  },
  {
    question: "Quantos graus Celsius é a temperatura do núcleo da Terra?",
    correctValue: 5200,
    unit: "graus Celsius",
    emoji: "🌡️",
  },
  {
    question: "Quantos quilômetros de profundidade tem o furo mais fundo já perfurado pelo homem?",
    correctValue: 12,
    unit: "quilômetros",
    emoji: "🕳️",
  },
  {
    question: "Quantos quilômetros de espessura tem a crosta terrestre nos continentes?",
    correctValue: 35,
    unit: "quilômetros",
    emoji: "🌍",
  },
  {
    question: "Quantos terremotos são registrados no mundo por ano?",
    correctValue: 500000,
    unit: "terremotos",
    emoji: "📉",
  },
  {
    question: "Quantos vulcões ativos existem no mundo?",
    correctValue: 1500,
    unit: "vulcões",
    emoji: "🌋",
  },
  {
    question: "Quantos graus Celsius atinge a lava de um vulcão?",
    correctValue: 1200,
    unit: "graus Celsius",
    emoji: "🔥",
  },
  {
    question: "Quantos quilômetros cúbicos de cinzas o vulcão Tambora expeliu em 1815?",
    correctValue: 150,
    unit: "km³",
    emoji: "🌋",
  },
  {
    question: "Quantos quilômetros por hora avança uma nuvem piroclástica?",
    correctValue: 700,
    unit: "km/h",
    emoji: "💨",
  },
  {
    question: "Quantos elementos químicos são metais na tabela periódica?",
    correctValue: 94,
    unit: "elementos",
    emoji: "🧲",
  },
  {
    question: "Quantos prótons tem o átomo de ouro?",
    correctValue: 79,
    unit: "prótons",
    emoji: "🪙",
  },
  {
    question: "Quantos quilates tem o ouro puro?",
    correctValue: 24,
    unit: "quilates",
    emoji: "💛",
  },
  {
    question: "Quantos graus na escala Mohs tem a dureza do diamante?",
    correctValue: 10,
    unit: "na escala Mohs",
    emoji: "💎",
  },
  {
    question: "Quantos bilhões de anos leva para o carbono virar diamante nas profundezas?",
    correctValue: 1,
    unit: "bilhão de anos",
    emoji: "💎",
  },
  {
    question: "Quantos quilômetros de profundidade se formam os diamantes naturais?",
    correctValue: 150,
    unit: "quilômetros",
    emoji: "⛏️",
  },
  {
    question: "Quantos litros de água são necessários para produzir uma única folha de papel A4?",
    correctValue: 10,
    unit: "litros",
    emoji: "📄",
  },
  {
    question: "Quantos anos leva para uma lata de alumínio se decompor na natureza?",
    correctValue: 200,
    unit: "anos",
    emoji: "🥫",
  },
  {
    question: "Quantos anos leva para uma bituca de cigarro se decompor?",
    correctValue: 5,
    unit: "anos",
    emoji: "🚬",
  },
  {
    question: "Quantos anos leva para o vidro se decompor na natureza, em milhares?",
    correctValue: 1,
    unit: "mil anos",
    emoji: "🍾",
  },
  {
    question: "Quantos quilos de CO2 uma árvore adulta absorve por ano?",
    correctValue: 22,
    unit: "quilos",
    emoji: "🌳",
  },
  {
    question: "Quantas partes por milhão de CO2 tem a atmosfera atualmente?",
    correctValue: 420,
    unit: "ppm",
    emoji: "🏭",
  },
  {
    question: "Quantos por cento da energia do Sol chega efetivamente à superfície da Terra?",
    correctValue: 48,
    unit: "por cento",
    emoji: "🔆",
  },
  {
    question: "Quantos watts de potência o corpo humano gera em repouso?",
    correctValue: 100,
    unit: "watts",
    emoji: "💡",
  },
  {
    question: "Quantos volts uma enguia elétrica consegue descarregar?",
    correctValue: 860,
    unit: "volts",
    emoji: "🐍",
  },
  {
    question: "Quantos quilômetros por hora atinge a queda livre de um paraquedista?",
    correctValue: 200,
    unit: "km/h",
    emoji: "🪂",
  },
  {
    question: "Quantos metros por segundo ao quadrado é a gravidade da Lua?",
    correctValue: 2,
    unit: "m/s²",
    emoji: "🌙",
  },
  {
    question: "Quantos quilômetros de circunferência tem o Grande Colisor de Hádrons?",
    correctValue: 27,
    unit: "quilômetros",
    emoji: "🔬",
  },
  {
    question: "Quantos graus Celsius abaixo de zero opera o Grande Colisor de Hádrons?",
    correctValue: 271,
    unit: "graus Celsius negativos",
    emoji: "🧊",
  },
  {
    question: "Quantos países financiam o CERN?",
    correctValue: 23,
    unit: "países",
    emoji: "🔬",
  },
  {
    question: "Quantos anos levou para o bóson de Higgs ser confirmado após ser previsto?",
    correctValue: 48,
    unit: "anos",
    emoji: "⚛️",
  },
  {
    question: "Quantos neutrinos atravessam o seu corpo por segundo, em trilhões?",
    correctValue: 100,
    unit: "trilhões de neutrinos",
    emoji: "👻",
  },

  // Biologia e animais exóticos
  {
    question: "Quantos corações tem uma minhoca?",
    correctValue: 5,
    unit: "corações",
    emoji: "🪱",
  },
  {
    question: "Quantos estômagos tem uma vaca?",
    correctValue: 4,
    unit: "estômagos",
    emoji: "🐄",
  },
  {
    question: "Quantos litros de saliva uma vaca produz por dia?",
    correctValue: 150,
    unit: "litros",
    emoji: "🐮",
  },
  {
    question: "Quantos músculos tem a tromba de um elefante?",
    correctValue: 40000,
    unit: "músculos",
    emoji: "🐘",
  },
  {
    question: "Quantos quilos de comida um elefante adulto consome por dia?",
    correctValue: 150,
    unit: "quilos",
    emoji: "🌿",
  },
  {
    question: "Quantos litros de água um camelo bebe em dez minutos?",
    correctValue: 100,
    unit: "litros",
    emoji: "🐫",
  },
  {
    question: "Quantos anos vive uma baleia-da-groenlândia?",
    correctValue: 200,
    unit: "anos",
    emoji: "🐋",
  },
  {
    question: "Quantos anos pode viver o tubarão-da-groenlândia?",
    correctValue: 400,
    unit: "anos",
    emoji: "🦈",
  },
  {
    question: "Quantos quilos pesa o coração de uma baleia-azul?",
    correctValue: 180,
    unit: "quilos",
    emoji: "🫀",
  },
  {
    question: "Quantos metros de comprimento atinge uma baleia-azul adulta?",
    correctValue: 30,
    unit: "metros",
    emoji: "🐳",
  },
  {
    question: "Quantos quilômetros uma baleia-cinzenta percorre em sua migração anual?",
    correctValue: 20000,
    unit: "quilômetros",
    emoji: "🌊",
  },
  {
    question: "Quantos metros de profundidade um cachalote consegue mergulhar?",
    correctValue: 2000,
    unit: "metros",
    emoji: "🐋",
  },
  {
    question: "Quantos minutos um cachalote aguenta sem respirar?",
    correctValue: 90,
    unit: "minutos",
    emoji: "⏱️",
  },
  {
    question: "Quantos tentáculos tem uma lula-gigante?",
    correctValue: 10,
    unit: "tentáculos",
    emoji: "🦑",
  },
  {
    question: "Quantos metros de comprimento atinge uma lula-colossal?",
    correctValue: 14,
    unit: "metros",
    emoji: "🦑",
  },
  {
    question: "Quantos ovos uma tartaruga marinha põe de uma só vez?",
    correctValue: 110,
    unit: "ovos",
    emoji: "🐢",
  },
  {
    question: "Quantos dentes tem um caracol, em milhares?",
    correctValue: 14,
    unit: "mil dentes",
    emoji: "🐌",
  },
  {
    question: "Quantos quilômetros por hora se move um caracol de jardim?",
    correctValue: 1,
    unit: "km/h",
    emoji: "🐌",
  },
  {
    question: "Quantas espécies de formigas já foram descritas pela ciência?",
    correctValue: 14000,
    unit: "espécies",
    emoji: "🐜",
  },
  {
    question: "Quantas vezes o próprio peso uma formiga consegue carregar?",
    correctValue: 50,
    unit: "vezes o próprio peso",
    emoji: "🐜",
  },
  {
    question: "Quantas formigas existem na Terra para cada ser humano?",
    correctValue: 2500000,
    unit: "formigas por pessoa",
    emoji: "🐜",
  },
  {
    question: "Quantas flores uma abelha visita para produzir um quilo de mel, em milhões?",
    correctValue: 4,
    unit: "milhões de flores",
    emoji: "🐝",
  },
  {
    question: "Quantos quilômetros uma abelha voa para produzir um quilo de mel, em milhares?",
    correctValue: 150,
    unit: "mil quilômetros",
    emoji: "🍯",
  },
  {
    question: "Quantas vezes por segundo uma abelha bate as asas?",
    correctValue: 230,
    unit: "vezes por segundo",
    emoji: "🐝",
  },
  {
    question: "Quantos ovos uma abelha rainha põe por dia?",
    correctValue: 2000,
    unit: "ovos",
    emoji: "👑",
  },
  {
    question: "Quantos olhos tem uma abelha?",
    correctValue: 5,
    unit: "olhos",
    emoji: "👁️",
  },
  {
    question: "Quantas facetas tem o olho composto de uma libélula?",
    correctValue: 30000,
    unit: "facetas",
    emoji: "🦟",
  },
  {
    question: "Quantos quilômetros a borboleta-monarca voa em sua migração?",
    correctValue: 4000,
    unit: "quilômetros",
    emoji: "🦋",
  },
  {
    question: "Quantas espécies de besouros já foram catalogadas?",
    correctValue: 400000,
    unit: "espécies",
    emoji: "🪲",
  },
  {
    question: "Quantos anos uma cigarra do gênero Magicicada passa no subsolo?",
    correctValue: 17,
    unit: "anos",
    emoji: "🦗",
  },
  {
    question: "Quantos quilômetros por hora mergulha um falcão-peregrino?",
    correctValue: 389,
    unit: "km/h",
    emoji: "🦅",
  },
  {
    question: "Quantos quilômetros o andorinhão-comum voa sem pousar, em milhares?",
    correctValue: 10,
    unit: "mil quilômetros",
    emoji: "🐦",
  },
  {
    question: "Quantos meses um albatroz consegue passar sem tocar em terra firme?",
    correctValue: 10,
    unit: "meses",
    emoji: "🕊️",
  },
  {
    question: "Quantos metros de envergadura tem o albatroz-errante?",
    correctValue: 3,
    unit: "metros",
    emoji: "🦅",
  },
  {
    question: "Quantos quilômetros a andorinha-do-ártico percorre por ano, em milhares?",
    correctValue: 70,
    unit: "mil quilômetros",
    emoji: "🐧",
  },
  {
    question: "Quantos graus Celsius abaixo de zero o pinguim-imperador suporta?",
    correctValue: 60,
    unit: "graus Celsius negativos",
    emoji: "🐧",
  },
  {
    question: "Quantos dias o pinguim-imperador macho choca o ovo sem comer?",
    correctValue: 65,
    unit: "dias",
    emoji: "🥚",
  },
  {
    question: "Quantos metros de profundidade um pinguim-imperador mergulha?",
    correctValue: 500,
    unit: "metros",
    emoji: "🌊",
  },
  {
    question: "Quantas espécies de tubarão existem no mundo?",
    correctValue: 500,
    unit: "espécies",
    emoji: "🦈",
  },
  {
    question: "Quantos dentes um tubarão troca ao longo da vida, em milhares?",
    correctValue: 30,
    unit: "mil dentes",
    emoji: "🦷",
  },
  {
    question: "Quantos metros de comprimento atinge o tubarão-baleia?",
    correctValue: 18,
    unit: "metros",
    emoji: "🐟",
  },
  {
    question: "Quantos ovos um bacalhau fêmea libera de uma vez, em milhões?",
    correctValue: 5,
    unit: "milhões de ovos",
    emoji: "🐟",
  },
  {
    question: "Quantos milivolts o tubarão detecta com seus receptores elétricos?",
    correctValue: 1,
    unit: "milivolt",
    emoji: "⚡",
  },
  {
    question: "Quantos anos vive uma esponja-do-mar do Antártico?",
    correctValue: 1500,
    unit: "anos",
    emoji: "🧽",
  },
  {
    question: "Quantos metros de comprimento atinge a água-viva-juba-de-leão?",
    correctValue: 36,
    unit: "metros",
    emoji: "🎐",
  },
  {
    question: "Quantas pessoas o veneno de uma vespa-do-mar pode matar?",
    correctValue: 60,
    unit: "pessoas",
    emoji: "☠️",
  },
  {
    question: "Quantos por cento do corpo de uma água-viva é água?",
    correctValue: 95,
    unit: "por cento",
    emoji: "💧",
  },
  {
    question: "Quantos anos vive um ouriço-do-mar-vermelho?",
    correctValue: 200,
    unit: "anos",
    emoji: "🦔",
  },
  {
    question: "Quantas espécies de bactérias vivem na boca de uma pessoa?",
    correctValue: 700,
    unit: "espécies",
    emoji: "🦠",
  },
  {
    question: "Quantos quilos de bactérias uma pessoa carrega no corpo?",
    correctValue: 2,
    unit: "quilos",
    emoji: "🧫",
  },
  {
    question: "Quantos anos o tardígrado consegue sobreviver sem água?",
    correctValue: 30,
    unit: "anos",
    emoji: "🐻",
  },
  {
    question: "Quantos graus Celsius o tardígrado suporta acima de zero?",
    correctValue: 150,
    unit: "graus Celsius",
    emoji: "🔥",
  },
  {
    question: "Quantos anos tem a árvore mais velha do mundo, o pinheiro Matusalém?",
    correctValue: 4850,
    unit: "anos",
    emoji: "🌲",
  },
  {
    question: "Quantos metros de altura tem a árvore mais alta do mundo, a sequoia Hyperion?",
    correctValue: 116,
    unit: "metros",
    emoji: "🌲",
  },
  {
    question: "Quantos litros de água uma sequoia-gigante bebe por dia?",
    correctValue: 2000,
    unit: "litros",
    emoji: "🌳",
  },
  {
    question: "Quantas espécies de árvores existem na Amazônia?",
    correctValue: 16000,
    unit: "espécies",
    emoji: "🌴",
  },
  {
    question: "Quantos anos leva para uma bananeira dar o primeiro cacho, em meses?",
    correctValue: 12,
    unit: "meses",
    emoji: "🍌",
  },
  {
    question: "Quantos quilos pesa a maior flor do mundo, a Rafflesia?",
    correctValue: 11,
    unit: "quilos",
    emoji: "🌺",
  },
  {
    question: "Quantos anos a flor-cadáver leva para florescer pela primeira vez?",
    correctValue: 10,
    unit: "anos",
    emoji: "🌸",
  },
  {
    question: "Quantas sementes tem uma única vagem de baunilha?",
    correctValue: 20000,
    unit: "sementes",
    emoji: "🌱",
  },

  // História, arqueologia e civilizações antigas
  {
    question: "Quantos blocos de pedra formam a Grande Pirâmide de Gizé, em milhões?",
    correctValue: 2,
    unit: "milhões de blocos",
    emoji: "🔺",
  },
  {
    question: "Quantos metros de altura tem a Grande Pirâmide de Gizé?",
    correctValue: 139,
    unit: "metros",
    emoji: "🏜️",
  },
  {
    question: "Quantos anos a Grande Pirâmide foi a construção mais alta do mundo?",
    correctValue: 3800,
    unit: "anos",
    emoji: "⏳",
  },
  {
    question: "Quantas toneladas pesa o maior bloco da Grande Pirâmide?",
    correctValue: 80,
    unit: "toneladas",
    emoji: "🪨",
  },
  {
    question: "Quantos anos durou o Império Romano do Ocidente?",
    correctValue: 507,
    unit: "anos",
    emoji: "🏛️",
  },
  {
    question: "Quantos espectadores cabiam no Coliseu de Roma?",
    correctValue: 50000,
    unit: "espectadores",
    emoji: "🏟️",
  },
  {
    question: "Quantos quilômetros de estradas o Império Romano construiu?",
    correctValue: 400000,
    unit: "quilômetros",
    emoji: "🛣️",
  },
  {
    question: "Quantos aquedutos abasteciam a cidade de Roma antiga?",
    correctValue: 11,
    unit: "aquedutos",
    emoji: "💧",
  },
  {
    question: "Quantos litros de água por dia os aquedutos levavam a Roma, em milhões?",
    correctValue: 1000,
    unit: "milhões de litros",
    emoji: "🚰",
  },
  {
    question: "Quantos imperadores romanos existiram ao todo?",
    correctValue: 70,
    unit: "imperadores",
    emoji: "👑",
  },
  {
    question: "Em que ano o Vesúvio soterrou a cidade de Pompeia?",
    correctValue: 79,
    unit: null,
    emoji: "🌋",
  },
  {
    question: "Quantos metros de cinzas cobriram Pompeia?",
    correctValue: 6,
    unit: "metros",
    emoji: "⛰️",
  },
  {
    question: "Quantos guerreiros formam o Exército de Terracota da China?",
    correctValue: 8000,
    unit: "guerreiros",
    emoji: "🗿",
  },
  {
    question: "Quantos anos o Exército de Terracota ficou enterrado até ser descoberto?",
    correctValue: 2200,
    unit: "anos",
    emoji: "⛏️",
  },
  {
    question: "Quantos anos durou a construção da Muralha da China?",
    correctValue: 2000,
    unit: "anos",
    emoji: "🧱",
  },
  {
    question: "Quantas pessoas morreram construindo a Muralha da China, em milhões?",
    correctValue: 1,
    unit: "milhão de pessoas",
    emoji: "⚰️",
  },
  {
    question: "Quantos metros de altura tem a pirâmide de Chichén Itzá?",
    correctValue: 30,
    unit: "metros",
    emoji: "🏛️",
  },
  {
    question: "Quantos degraus tem a pirâmide de Kukulcán, em Chichén Itzá?",
    correctValue: 365,
    unit: "degraus",
    emoji: "🪜",
  },
  {
    question: "Quantos metros de altitude está Machu Picchu?",
    correctValue: 2430,
    unit: "metros",
    emoji: "⛰️",
  },
  {
    question: "Quantos anos Machu Picchu ficou esquecido antes de ser redescoberto?",
    correctValue: 400,
    unit: "anos",
    emoji: "🌿",
  },
  {
    question: "Quantos quilômetros tinha a rede de estradas do Império Inca?",
    correctValue: 40000,
    unit: "quilômetros",
    emoji: "🥾",
  },
  {
    question: "Quantas estátuas moai existem na Ilha de Páscoa?",
    correctValue: 887,
    unit: "estátuas",
    emoji: "🗿",
  },
  {
    question: "Quantas toneladas pesa o maior moai já erguido?",
    correctValue: 82,
    unit: "toneladas",
    emoji: "🗿",
  },
  {
    question: "Quantas pedras formam o círculo de Stonehenge?",
    correctValue: 93,
    unit: "pedras",
    emoji: "🪨",
  },
  {
    question: "Quantos quilômetros as pedras de Stonehenge foram transportadas?",
    correctValue: 250,
    unit: "quilômetros",
    emoji: "🚚",
  },
  {
    question: "Quantos anos tem as pinturas rupestres da caverna de Lascaux?",
    correctValue: 17000,
    unit: "anos",
    emoji: "🎨",
  },
  {
    question: "Quantos anos tem o sítio arqueológico de Göbekli Tepe?",
    correctValue: 11000,
    unit: "anos",
    emoji: "🏺",
  },
  {
    question: "Quantos anos tem a múmia de Ötzi, o homem do gelo?",
    correctValue: 5300,
    unit: "anos",
    emoji: "🧊",
  },
  {
    question: "Quantas tatuagens foram encontradas no corpo de Ötzi?",
    correctValue: 61,
    unit: "tatuagens",
    emoji: "🖋️",
  },
  {
    question: "Quantos objetos foram encontrados na tumba de Tutancâmon?",
    correctValue: 5398,
    unit: "objetos",
    emoji: "⚱️",
  },
  {
    question: "Quantos quilos pesa a máscara funerária de Tutancâmon?",
    correctValue: 10,
    unit: "quilos",
    emoji: "🎭",
  },
  {
    question: "Quantos anos tinha Tutancâmon quando morreu?",
    correctValue: 19,
    unit: "anos",
    emoji: "👑",
  },
  {
    question: "Quantos anos Cleópatra tinha quando se tornou rainha do Egito?",
    correctValue: 18,
    unit: "anos",
    emoji: "👸",
  },
  {
    question: "Quantos rolos tinha a Biblioteca de Alexandria, em milhares?",
    correctValue: 400,
    unit: "mil rolos",
    emoji: "📜",
  },
  {
    question: "Quantas maravilhas do mundo antigo existiam?",
    correctValue: 7,
    unit: "maravilhas",
    emoji: "🏛️",
  },
  {
    question: "Quantos metros de altura tinha o Colosso de Rodes?",
    correctValue: 33,
    unit: "metros",
    emoji: "🗽",
  },
  {
    question: "Quantos anos durou a Guerra dos Cem Anos?",
    correctValue: 116,
    unit: "anos",
    emoji: "⚔️",
  },
  {
    question: "Quantos minutos durou a guerra mais curta da história, entre Inglaterra e Zanzibar?",
    correctValue: 38,
    unit: "minutos",
    emoji: "🏳️",
  },
  {
    question: "Quantos por cento da população europeia a Peste Negra matou?",
    correctValue: 50,
    unit: "por cento",
    emoji: "🐀",
  },
  {
    question: "Quantos anos durou a Guerra dos Trinta Anos?",
    correctValue: 30,
    unit: "anos",
    emoji: "🛡️",
  },
  {
    question: "Quantos navios formavam a Invencível Armada espanhola?",
    correctValue: 130,
    unit: "navios",
    emoji: "⛵",
  },
  {
    question: "Quantos dias durou a viagem de Colombo até a América em 1492?",
    correctValue: 70,
    unit: "dias",
    emoji: "🚢",
  },
  {
    question: "Quantos homens sobreviveram à primeira volta ao mundo de Fernão de Magalhães?",
    correctValue: 18,
    unit: "homens",
    emoji: "🧭",
  },
  {
    question: "Quantos anos durou a viagem de circum-navegação de Magalhães, em dias?",
    correctValue: 1082,
    unit: "dias",
    emoji: "🌎",
  },
  {
    question: "Em que ano o Brasil deixou de ser colônia de Portugal?",
    correctValue: 1822,
    unit: null,
    emoji: "🇧🇷",
  },
  {
    question: "Quantos anos durou o período imperial no Brasil?",
    correctValue: 67,
    unit: "anos",
    emoji: "👑",
  },
  {
    question: "Quantas pessoas foram trazidas ao Brasil pelo tráfico de escravizados, em milhões?",
    correctValue: 5,
    unit: "milhões de pessoas",
    emoji: "⛓️",
  },
  {
    question: "Quantos anos durou a Guerra de Canudos, em meses?",
    correctValue: 11,
    unit: "meses",
    emoji: "🏜️",
  },
  {
    question: "Quantos presidentes o Brasil já teve?",
    correctValue: 39,
    unit: "presidentes",
    emoji: "🏛️",
  },
  {
    question: "Quantos anos durou a construção de Brasília, em meses?",
    correctValue: 41,
    unit: "meses",
    emoji: "🏗️",
  },
  {
    question: "Quantos anos durou a Primeira Guerra Mundial, em meses?",
    correctValue: 52,
    unit: "meses",
    emoji: "🎖️",
  },
  {
    question: "Quantas pessoas morreram na gripe espanhola de 1918, em milhões?",
    correctValue: 50,
    unit: "milhões de pessoas",
    emoji: "😷",
  },
  {
    question: "Quantos anos o Muro de Berlim ficou de pé?",
    correctValue: 28,
    unit: "anos",
    emoji: "🧱",
  },
  {
    question: "Quantos quilômetros de extensão tinha o Muro de Berlim?",
    correctValue: 155,
    unit: "quilômetros",
    emoji: "🚧",
  },
  {
    question: "Quantos anos durou a União Soviética?",
    correctValue: 69,
    unit: "anos",
    emoji: "☭",
  },
  {
    question: "Quantos anos Nelson Mandela ficou preso?",
    correctValue: 27,
    unit: "anos",
    emoji: "✊",
  },
  {
    question: "Quantos dias durou a Revolução dos Cravos, em Portugal?",
    correctValue: 1,
    unit: "dia",
    emoji: "🌸",
  },
  {
    question: "Quantos idiomas oficiais tinha o Império Austro-Húngaro?",
    correctValue: 11,
    unit: "idiomas",
    emoji: "🗣️",
  },
  {
    question: "Quantos anos durou a dinastia dos faraós no Egito, em milhares?",
    correctValue: 3,
    unit: "mil anos",
    emoji: "🐫",
  },
  {
    question: "Quantos hieróglifos diferentes existiam na escrita egípcia?",
    correctValue: 1000,
    unit: "hieróglifos",
    emoji: "📖",
  },

  // Geografia extrema e recordes
  {
    question: "Quantos graus Celsius abaixo de zero foi a temperatura mais baixa já registrada na Terra?",
    correctValue: 89,
    unit: "graus Celsius negativos",
    emoji: "🥶",
  },
  {
    question: "Quantos graus Celsius foi a temperatura mais alta já registrada na Terra?",
    correctValue: 56,
    unit: "graus Celsius",
    emoji: "🥵",
  },
  {
    question: "Quantos milímetros de chuva por ano caem no deserto do Atacama?",
    correctValue: 1,
    unit: "milímetro",
    emoji: "🏜️",
  },
  {
    question: "Quantos metros abaixo do nível do mar está o Mar Morto?",
    correctValue: 430,
    unit: "metros",
    emoji: "🧂",
  },
  {
    question: "Quantos gramas de sal tem um litro de água do Mar Morto?",
    correctValue: 340,
    unit: "gramas",
    emoji: "🧂",
  },
  {
    question: "Quantos metros de profundidade tem o lago Baikal?",
    correctValue: 1642,
    unit: "metros",
    emoji: "🏞️",
  },
  {
    question: "Quantos por cento da água doce líquida do mundo está no lago Baikal?",
    correctValue: 20,
    unit: "por cento",
    emoji: "💧",
  },
  {
    question: "Quantos quilômetros quadrados tem o deserto do Saara, em milhões?",
    correctValue: 9,
    unit: "milhões de km²",
    emoji: "🐪",
  },
  {
    question: "Quantos metros de altura atingem as dunas mais altas do Saara?",
    correctValue: 180,
    unit: "metros",
    emoji: "🏜️",
  },
  {
    question: "Quantos quilômetros de extensão tem a Cordilheira dos Andes?",
    correctValue: 7000,
    unit: "quilômetros",
    emoji: "🏔️",
  },
  {
    question: "Quantos metros de altura tem o Aconcágua, o pico mais alto das Américas?",
    correctValue: 6961,
    unit: "metros",
    emoji: "⛰️",
  },
  {
    question: "Quantas pessoas já chegaram ao cume do Everest?",
    correctValue: 6000,
    unit: "pessoas",
    emoji: "🧗",
  },
  {
    question: "Quantos centímetros o Everest cresce por ano?",
    correctValue: 1,
    unit: "centímetro",
    emoji: "📏",
  },
  {
    question: "Quantos quilômetros de extensão tem a Grande Barreira de Corais?",
    correctValue: 2300,
    unit: "quilômetros",
    emoji: "🐠",
  },
  {
    question: "Quantos por cento da vida marinha depende dos recifes de coral?",
    correctValue: 25,
    unit: "por cento",
    emoji: "🪸",
  },
  {
    question: "Quantas ilhas tem a Indonésia?",
    correctValue: 17000,
    unit: "ilhas",
    emoji: "🏝️",
  },
  {
    question: "Quantas ilhas tem a Finlândia, em milhares?",
    correctValue: 180,
    unit: "mil ilhas",
    emoji: "🇫🇮",
  },
  {
    question: "Quantos lagos existem no Canadá, em milhões?",
    correctValue: 2,
    unit: "milhões de lagos",
    emoji: "🇨🇦",
  },
  {
    question: "Quantos quilômetros de fronteira o Brasil tem com outros países?",
    correctValue: 16880,
    unit: "quilômetros",
    emoji: "🗺️",
  },
  {
    question: "Quantos países fazem fronteira com o Brasil?",
    correctValue: 10,
    unit: "países",
    emoji: "🌎",
  },
  {
    question: "Quantos hectares tem o Vaticano, o menor país do mundo?",
    correctValue: 44,
    unit: "hectares",
    emoji: "⛪",
  },
  {
    question: "Quantos habitantes tem o Vaticano?",
    correctValue: 800,
    unit: "habitantes",
    emoji: "🕊️",
  },
  {
    question: "Quantos metros de comprimento tem a rua mais curta do mundo, na Escócia?",
    correctValue: 2,
    unit: "metros",
    emoji: "🛣️",
  },
  {
    question: "Quantos quilômetros de extensão tem a Transiberiana?",
    correctValue: 9289,
    unit: "quilômetros",
    emoji: "🚂",
  },
  {
    question: "Quantos dias dura a viagem completa da ferrovia Transiberiana?",
    correctValue: 7,
    unit: "dias",
    emoji: "🚆",
  },
  {
    question: "Quantos metros de altura tem a cachoeira Kaieteur, na Guiana?",
    correctValue: 226,
    unit: "metros",
    emoji: "💦",
  },
  {
    question: "Quantas quedas d'água formam as Cataratas do Iguaçu?",
    correctValue: 275,
    unit: "quedas",
    emoji: "🌈",
  },
  {
    question: "Quantos metros de profundidade tem a caverna mais funda do mundo, a Veryovkina?",
    correctValue: 2212,
    unit: "metros",
    emoji: "🕳️",
  },
  {
    question: "Quantos quilômetros de galerias tem a Caverna Mamute, nos Estados Unidos?",
    correctValue: 675,
    unit: "quilômetros",
    emoji: "🦇",
  },
  {
    question: "Quantos anos leva para se formar um estalactite de um centímetro?",
    correctValue: 100,
    unit: "anos",
    emoji: "🗿",
  },
  {
    question: "Quantos habitantes por quilômetro quadrado tem Mônaco?",
    correctValue: 19000,
    unit: "habitantes por km²",
    emoji: "🎰",
  },
  {
    question: "Quantos andares tem o edifício residencial mais alto do mundo, em Nova York?",
    correctValue: 131,
    unit: "andares",
    emoji: "🏢",
  },
  {
    question: "Quantos elevadores tem o Burj Khalifa?",
    correctValue: 57,
    unit: "elevadores",
    emoji: "🛗",
  },
  {
    question: "Quantos degraus tem a Torre Eiffel até o topo?",
    correctValue: 1665,
    unit: "degraus",
    emoji: "🗼",
  },
  {
    question: "Quantos centímetros a Torre Eiffel cresce no verão por dilatação?",
    correctValue: 15,
    unit: "centímetros",
    emoji: "🌡️",
  },
  {
    question: "Quantos rebites foram usados na construção da Torre Eiffel, em milhões?",
    correctValue: 3,
    unit: "milhões de rebites",
    emoji: "🔩",
  },
  {
    question: "Quantos graus a Torre de Pisa está inclinada?",
    correctValue: 4,
    unit: "graus",
    emoji: "🏛️",
  },
  {
    question: "Quantos quilômetros de túneis existem sob a cidade de Paris?",
    correctValue: 300,
    unit: "quilômetros",
    emoji: "💀",
  },
  {
    question: "Quantos esqueletos estão nas catacumbas de Paris, em milhões?",
    correctValue: 6,
    unit: "milhões de esqueletos",
    emoji: "☠️",
  },
  {
    question: "Quantas pontes existem na cidade de Veneza?",
    correctValue: 400,
    unit: "pontes",
    emoji: "🚤",
  },

  // Tecnologia, cultura e curiosidades obscuras
  {
    question: "Quantos transistores tem um processador moderno de celular, em bilhões?",
    correctValue: 16,
    unit: "bilhões de transistores",
    emoji: "📱",
  },
  {
    question: "Quantos quilos pesava o primeiro computador eletrônico, o ENIAC?",
    correctValue: 27000,
    unit: "quilos",
    emoji: "💻",
  },
  {
    question: "Quantas válvulas tinha o computador ENIAC?",
    correctValue: 17468,
    unit: "válvulas",
    emoji: "🔌",
  },
  {
    question: "Quantos quilobytes de memória tinha o computador da Apollo 11?",
    correctValue: 64,
    unit: "kilobytes",
    emoji: "🌕",
  },
  {
    question: "Quantos quilos pesava o primeiro celular comercial, de 1983?",
    correctValue: 1,
    unit: "quilo",
    emoji: "☎️",
  },
  {
    question: "Quantos dólares custava o primeiro celular comercial da Motorola?",
    correctValue: 3995,
    unit: "dólares",
    emoji: "💵",
  },
  {
    question: "Em que ano foi enviado o primeiro e-mail da história?",
    correctValue: 1971,
    unit: null,
    emoji: "📧",
  },
  {
    question: "Em que ano surgiu o primeiro site da World Wide Web?",
    correctValue: 1991,
    unit: null,
    emoji: "🌐",
  },
  {
    question: "Quantos caracteres tinha o limite original de um tweet?",
    correctValue: 140,
    unit: "caracteres",
    emoji: "🐦",
  },
  {
    question: "Quantos idiomas o Google Tradutor suporta?",
    correctValue: 130,
    unit: "idiomas",
    emoji: "🔤",
  },
  {
    question: "Quantos quilômetros de cabos submarinos conectam a internet mundial, em milhares?",
    correctValue: 1400,
    unit: "mil quilômetros",
    emoji: "🔌",
  },
  {
    question: "Quantos por cento do tráfego da internet passa por cabos submarinos?",
    correctValue: 99,
    unit: "por cento",
    emoji: "🌊",
  },
  {
    question: "Quantos data centers a Google opera no mundo?",
    correctValue: 40,
    unit: "data centers",
    emoji: "🏢",
  },
  {
    question: "Quantos bitcoins existirão no total, em milhões?",
    correctValue: 21,
    unit: "milhões de bitcoins",
    emoji: "₿",
  },
  {
    question: "Em que ano o primeiro bloco do Bitcoin foi minerado?",
    correctValue: 2009,
    unit: null,
    emoji: "⛏️",
  },
  {
    question: "O total de partidas de xadrez possíveis é 10 elevado a qual número?",
    correctValue: 120,
    unit: "(expoente de 10)",
    emoji: "♟️",
  },
  {
    question: "Quantas combinações possíveis tem um cubo mágico, em quintilhões?",
    correctValue: 43,
    unit: "quintilhões",
    emoji: "🧩",
  },
  {
    question: "Quantos segundos é o recorde mundial de resolução do cubo mágico?",
    correctValue: 3,
    unit: "segundos",
    emoji: "⏱️",
  },
  {
    question: "Quantas peças tem o maior quebra-cabeça comercial do mundo?",
    correctValue: 54000,
    unit: "peças",
    emoji: "🧩",
  },
  {
    question: "Quantas casas decimais de pi já foram calculadas, em trilhões?",
    correctValue: 100,
    unit: "trilhões de casas",
    emoji: "🥧",
  },
  {
    question: "Quantas casas decimais de pi o recordista humano já recitou de memória?",
    correctValue: 70000,
    unit: "casas decimais",
    emoji: "🧠",
  },
  {
    question: "Quantos dígitos tem o maior número primo já descoberto, em milhões?",
    correctValue: 41,
    unit: "milhões de dígitos",
    emoji: "🔢",
  },
  {
    question: "Quantas línguas diferentes já receberam tradução da Bíblia?",
    correctValue: 700,
    unit: "idiomas",
    emoji: "📕",
  },
  {
    question: "Quantas palavras tem o dicionário da língua portuguesa, em milhares?",
    correctValue: 400,
    unit: "mil palavras",
    emoji: "📚",
  },
  {
    question: "Quantas palavras uma pessoa fala por dia, em média?",
    correctValue: 16000,
    unit: "palavras",
    emoji: "💬",
  },
  {
    question: "Quantos caracteres tem o idioma chinês, em milhares?",
    correctValue: 50,
    unit: "mil caracteres",
    emoji: "🀄",
  },
  {
    question: "Quantos caracteres chineses são necessários para ler um jornal?",
    correctValue: 3000,
    unit: "caracteres",
    emoji: "📰",
  },
  {
    question: "Quantos anos levou para Michelangelo pintar o teto da Capela Sistina?",
    correctValue: 4,
    unit: "anos",
    emoji: "🎨",
  },
  {
    question: "Quantas figuras humanas Michelangelo pintou no teto da Capela Sistina?",
    correctValue: 300,
    unit: "figuras",
    emoji: "🖼️",
  },
  {
    question: "Quantos centímetros de largura tem o quadro da Mona Lisa?",
    correctValue: 53,
    unit: "centímetros",
    emoji: "🖼️",
  },
  {
    question: "Quantas pessoas visitam o Museu do Louvre por ano, em milhões?",
    correctValue: 9,
    unit: "milhões de pessoas",
    emoji: "🏛️",
  },
  {
    question: "Quantas obras de arte o Museu do Louvre abriga, em milhares?",
    correctValue: 500,
    unit: "mil obras",
    emoji: "🖌️",
  },
  {
    question: "Quantos quadros Vincent van Gogh vendeu enquanto estava vivo?",
    correctValue: 1,
    unit: "quadro",
    emoji: "🌻",
  },
  {
    question: "Quantas obras Vincent van Gogh pintou ao longo da vida?",
    correctValue: 900,
    unit: "obras",
    emoji: "🎨",
  },
  {
    question: "Quantas sinfonias Beethoven compôs?",
    correctValue: 9,
    unit: "sinfonias",
    emoji: "🎼",
  },
  {
    question: "Quantas obras Mozart compôs ao longo da vida?",
    correctValue: 626,
    unit: "obras",
    emoji: "🎻",
  },
  {
    question: "Quantos anos tinha Mozart quando compôs sua primeira peça?",
    correctValue: 5,
    unit: "anos",
    emoji: "🎹",
  },
  {
    question: "Quantas peças de teatro Shakespeare escreveu?",
    correctValue: 39,
    unit: "peças",
    emoji: "🎭",
  },
  {
    question: "Quantas palavras Shakespeare inventou e introduziu no inglês?",
    correctValue: 1700,
    unit: "palavras",
    emoji: "✒️",
  },
  {
    question: "Quantos idiomas o livro O Pequeno Príncipe já foi traduzido?",
    correctValue: 500,
    unit: "idiomas",
    emoji: "🤴",
  },
  {
    question: "Quantos exemplares de Dom Quixote já foram vendidos, em milhões?",
    correctValue: 500,
    unit: "milhões de exemplares",
    emoji: "🐴",
  },
  {
    question: "Quantas páginas tem o livro Em Busca do Tempo Perdido, de Proust?",
    correctValue: 3000,
    unit: "páginas",
    emoji: "📖",
  },
  {
    question: "Quantos anos levou para o dicionário Oxford ser concluído pela primeira vez?",
    correctValue: 70,
    unit: "anos",
    emoji: "📔",
  },
  {
    question: "Quantos filmes foram produzidos em Bollywood no ano de pico?",
    correctValue: 1800,
    unit: "filmes",
    emoji: "🎬",
  },
  {
    question: "Quantos minutos dura o filme mais longo já lançado comercialmente?",
    correctValue: 873,
    unit: "minutos",
    emoji: "🍿",
  },
  {
    question: "Quantos dias durou a filmagem de O Poderoso Chefão?",
    correctValue: 77,
    unit: "dias",
    emoji: "🎥",
  },
  {
    question: "Quantas indicações ao Oscar tem o recorde dividido por Titanic e La La Land?",
    correctValue: 14,
    unit: "indicações",
    emoji: "🏆",
  },
  {
    question: "Quantos episódios tem a série animada Os Simpsons?",
    correctValue: 790,
    unit: "episódios",
    emoji: "🍩",
  },
  {
    question: "Quantos anos o programa de TV mais longo do mundo está no ar?",
    correctValue: 75,
    unit: "anos",
    emoji: "📺",
  },
  {
    question: "Quantos ingressos de cinema são vendidos por ano na Índia, em bilhões?",
    correctValue: 2,
    unit: "bilhões de ingressos",
    emoji: "🎟️",
  },
  {
    question: "Quantas notas musicais diferentes um piano de cauda produz por oitava?",
    correctValue: 12,
    unit: "notas",
    emoji: "🎹",
  },
  {
    question: "Quantas cordas tem uma harpa de concerto?",
    correctValue: 47,
    unit: "cordas",
    emoji: "🎵",
  },
  {
    question: "Quantos músicos formam uma orquestra sinfônica completa?",
    correctValue: 100,
    unit: "músicos",
    emoji: "🎺",
  },
  {
    question: "Quantos quilos pesa o maior instrumento musical do mundo, um órgão?",
    correctValue: 150000,
    unit: "quilos",
    emoji: "🎹",
  },
  {
    question: "Quantos tubos tem o maior órgão de tubos do mundo, em milhares?",
    correctValue: 33,
    unit: "mil tubos",
    emoji: "⛪",
  },
  {
    question: "Quantos anos de treinamento um sumô leva para chegar ao topo, em média?",
    correctValue: 10,
    unit: "anos",
    emoji: "🤼",
  },
  {
    question: "Quantas calorias um lutador de sumô consome por dia?",
    correctValue: 7000,
    unit: "calorias",
    emoji: "🍚",
  },
  {
    question: "Quantos quilômetros por hora atinge uma bola de golfe em um drive profissional?",
    correctValue: 290,
    unit: "km/h",
    emoji: "⛳",
  },
  {
    question: "Quantas covinhas tem uma bola de golfe?",
    correctValue: 336,
    unit: "covinhas",
    emoji: "🏌️",
  },
  {
    question: "Quantos pontos tem a costura de uma bola de beisebol?",
    correctValue: 108,
    unit: "pontos",
    emoji: "⚾",
  },
];
